#include "rengine.h"

using namespace rengine;

RENGINE_ALLOCATION_POOL_DEFINITION(Node);
RENGINE_ALLOCATION_POOL_DEFINITION(TransformNode);
RENGINE_ALLOCATION_POOL_DEFINITION(OpacityNode);
RENGINE_ALLOCATION_POOL_DEFINITION(LayerNode);
RENGINE_ALLOCATION_POOL_DEFINITION(RectangleNode);
RENGINE_ALLOCATION_POOL_DEFINITION(ColorFilterNode);